export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";
export const CREATE_APPOINTMENTS = "CREATE_APPOINTMENTS";
export const EDIT_APPOINTMENTS = "EDIT_APPOINTMENTS";
export const EDIT_APPOINTMENTS_DATA = "EDIT_APPOINTMENTS_DATA";